@startuml
skinparam classAttributeIconSize 0
!theme blueprint



/' Objects '/

class invalid_day {
	+invalid_day(std::string)
}


class invalid_month {
	+invalid_month(std::string)
}


class invalid_year {
	+invalid_year(std::string)
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
