@startuml date
skinparam classAttributeIconSize 0


/' Objects '/

class Date {
	+Date(int month, int day, int year, weekdayType weekday)
	~Date()
	+isLeapYear() : bool
	+findFirstSpecificWeekdayDay(weekdayType weekdayToFind) : Date&
	+countSpecificWeekday(const Date& firstSpecificWeekdayDay) : const int
	+operator!=(const Date& otherDate) const : bool
	+operator<(const Date& otherDate) const : bool
	+operator<=(const Date& otherDate) const : bool
	+operator==(const Date& otherDate) const : bool
	+operator>(const Date& otherDate) const : bool
	+operator>=(const Date& otherDate) const : bool
	+operator++() : Date
	+operator++(int) : Date
	+operator--() : Date
	+operator--(int) : Date
	+operator+(int daysToAdd) : Date&
	+operator-(int daysToSub) : Date&
	+getDay() const : int
	+getMonth() const : int
	+getYear() const : int
	+getWeekday() const : weekdayType
	+setDay(int day) : void
	+setMonth(int month) : void
	+setYear(int year) : void
	+setWeekday(weekdayType) : void
    +friend operator+(int daysToAdd, Date& addToDate) : Date&
	+friend operator-(int daysToSub, Date& subFromDate) : Date&
	+friend operator>>(std::istream& in, Date& dateToFill) : std::istream&
	+friend operator<<(std::ostream& out, Date& dateToPrint) : std::ostream&
    -day : int
    -month : int
    -year : int
    -weekday : weekdayType
    -weekdayIndices : const int [7]
    -weekdayType : enum

}

enum weekdayType {
SUNDAY,
MONDAY,
TUESDAY,
WEDNESDAY,
THURSDAY,
FRIDAY,
SATURDAY
}

/' Inheritance relationships '/




/' Aggregation relationships '/

Date *-- weekdayType

/' Nested objects '/


@enduml